; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Mon Sep 18 2017 21:26:03 GMT+0200 (Mitteleuropäische Sommerzeit)

; Clear any bed transform
M561
G29 S2

; Home all axes
G28

; Grid compensation
M98 P/sys/bed_probe.g