; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Mon Sep 18 2017 21:26:03 GMT+0200 (Mitteleuropäische Sommerzeit)

M703 ; load filament settings

; Wait for set temperatures to be reached
M116 P0
